name = "app"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.5.1 and < 6.0.0"
lustre_websocket = ">= 0.9.0 and < 1.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_time = ">= 1.6.0 and < 2.0.0"
lustre_dev_tools = ">= 2.3.4 and < 3.0.0"
rsvp = ">= 1.2.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"

[tools.lustre.bin]
# Remove this field to force Lustre to download its own toolchain, not your system's.
bun = "/home/grassjelly/.bun/bin/bun"

[dev-dependencies]
gleeunit = ">= 1.9.0 and < 2.0.0"
